project_id = "dnyxuzyvpoeuwvwauekj"

[functions.check-order-status]
verify_jwt = false

[functions.get-livesklad-products]
verify_jwt = false

[functions.send-telegram-order]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false
